name: "New APK"

on:
  workflow_dispatch:

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Prepare env"
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
          KEYSTORE_PROPS_B64: ${{ secrets.KEYSTORE_PROPS_B64 }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          echo "$KEYSTORE_B64" | base64 -d | zcat >> androidApp/keyguard-release.keystore
          echo "$KEYSTORE_PROPS_B64" | base64 -d | zcat >> androidApp/keyguard-release.properties
          echo "$GOOGLE_SERVICES" | base64 -d | zcat >> androidApp/google-services.json
          echo "" >> gradle.properties
          echo "versionRef=$(git rev-parse --short HEAD)" >> gradle.properties
          echo buildkonfig.flavor=release >> gradle.properties
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
      - name: "Check and Build licenses"
        run: ./gradlew :androidApp:licenseeAndroidNoneRelease
      - name: "Move licenses"
        run: |
          mv -f androidApp/build/reports/licensee/androidNoneRelease/artifacts.json common/src/commonMain/composeResources/files/licenses.json
      - name: "Build"
        run: ./gradlew :androidApp:assembleNoneRelease
      - name: "Find file .apk path"
        id: find-file
        run: | 
          file=$(find androidApp/build/outputs/apk -name '*.apk' | head -n 1)
          if [ -z "$file" ]; then
            echo "No .apk files found"
            exit 1
          fi
          echo "file_path=$file" >> $GITHUB_OUTPUT
      - name: 'Upload .apk'
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ${{ steps.find-file.outputs.file_path }}
          retention-days: 7
